// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadVisualiser returns the embedded CollectionSpec for visualiser.
func loadVisualiser() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_VisualiserBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load visualiser: %w", err)
	}

	return spec, err
}

// loadVisualiserObjects loads visualiser and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*visualiserObjects
//	*visualiserPrograms
//	*visualiserMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadVisualiserObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadVisualiser()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// visualiserSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type visualiserSpecs struct {
	visualiserProgramSpecs
	visualiserMapSpecs
	visualiserVariableSpecs
}

// visualiserProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type visualiserProgramSpecs struct {
	TcpConnect *ebpf.ProgramSpec `ebpf:"tcp_connect"`
}

// visualiserMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type visualiserMapSpecs struct {
	ConnEvents *ebpf.MapSpec `ebpf:"conn_events"`
}

// visualiserVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type visualiserVariableSpecs struct {
}

// visualiserObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadVisualiserObjects or ebpf.CollectionSpec.LoadAndAssign.
type visualiserObjects struct {
	visualiserPrograms
	visualiserMaps
	visualiserVariables
}

func (o *visualiserObjects) Close() error {
	return _VisualiserClose(
		&o.visualiserPrograms,
		&o.visualiserMaps,
	)
}

// visualiserMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadVisualiserObjects or ebpf.CollectionSpec.LoadAndAssign.
type visualiserMaps struct {
	ConnEvents *ebpf.Map `ebpf:"conn_events"`
}

func (m *visualiserMaps) Close() error {
	return _VisualiserClose(
		m.ConnEvents,
	)
}

// visualiserVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadVisualiserObjects or ebpf.CollectionSpec.LoadAndAssign.
type visualiserVariables struct {
}

// visualiserPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadVisualiserObjects or ebpf.CollectionSpec.LoadAndAssign.
type visualiserPrograms struct {
	TcpConnect *ebpf.Program `ebpf:"tcp_connect"`
}

func (p *visualiserPrograms) Close() error {
	return _VisualiserClose(
		p.TcpConnect,
	)
}

func _VisualiserClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed visualiser_bpfeb.o
var _VisualiserBytes []byte
